### PR TITLE
Fix Overflow from Footer

### LINKED ISSUE #260: width > 100%
For some reason some of our elements float out of the page width (even on very wide screens) on firefox. See the scroll-bar on the bottom. It is not visible what exactly is causing this, but it is present on all pages.

image

### PR DESCRIPTION
**Pull request by shawntabrizi**
Fixes #260 

CC @kaichaosun

### CODE REVIEW

File: website/core/Footer.js [hunk 1]
```diff
@@ -132,37 +131,31 @@ class Footer extends React.Component {
...
-        <section className="row">
-          <div className="copyright">{this.props.config.copyright}</div>
-          <a className="item" href="https://www.parity.io/privacy/">Privacy Policy</a>
-          <a className="item" href="#" id="cookie-settings">Cookie Settings</a>
-          <script
-            dangerouslySetInnerHTML={{
-              __html: `
+        <section className="copyright">{this.props.config.copyright}</section>
+
+        <script
```
Comment (kaichaosun) [inline website/core/Footer.js]: Will it be better if put the script near the element?

Comment (shawntabrizi) [reply website/core/Footer.js]: it doesn't matter right?

I could put a comment on the script saying they are related

Comment (shawntabrizi) [reply website/core/Footer.js]: I moved the script right into the `a` tag and also put a note :)
